### ISSUE TITLE
你好，利用训练好的模型去预测自己的数据，待预测的数据要改成什么样子，直接输入没有标点符号的句子报下面的错误，问一下这个怎么解决？

### ISSUE THREAD

**Issue by liupengstyle** [MenNianShi/PunctuationPrediction-BERT#6]

**Comment by liupengstyle** [comment]
Traceback (most recent call last):
File "cn_punctor.py", line 1227, in
main()
File "cn_punctor.py", line 1141, in main
out_str, f1, err, ser = compute_score(target_path,predict_path)
File "cn_punctor.py", line 1212, in compute_score
err = round((100.0 - float(total_correct) / float(counter - 1) * 100.0), 2)
ZeroDivisionError: float division by zero
INFO:tensorflow:prediction_loop marked as finished

**Comment by MenNianShi** [comment]
参考https://github.com/MenNianShi/PunctuationPrediction-BERT/blob/master/data/bert_prepro.py
生成训练/验证/测试集
